.github/workflows/deploy.yml
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> change owner for deploy master

.github/workflows/deploy.yml
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> repaird wrong owner name

components/SideNavigation.vue
- [issue#18](https://github.com/MeditationDuck/covid19/issues/18) の修正プルリクです。
- (なし)
- 「新型コロナウイルス感染症に関する情報」へのリンク切れを修正しました。
- (なし)
=> 「新型コロナウイルス感染症に関する情報」へのリンク切れを修正しました。

.github/workflows/deploy.yml, components/SideNavigation.vue
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> changed deploy.yml

README.md
- close #20 
- staging のURLが無いので「設置中」と記載
=> README.md を 岩手版 に書き換える

README.md
- close #20 
- https://staging-covid19-iwate.netlify.com/ を明記
- iwate.stopcovid19.jp ドメインは削除
=> README.md にステージングのURLを追加

README.md, components/DevelopmentModeMark.vue, layouts/default.vue, layouts/print.vue, nuxt.config.ts
=> 公開URLを https://iwate.stopcovid19.jp/ に変更

data/news.json
=> news.json に岩手県知事メッセージへのリンクを追加する

data/news.json
- close #77
- トップページ上部に [第8回本部員会議 知事メッセージ（令和2年4月3日）](https://www.pref.iwate.jp/kurashikankyou/iryou/kenkou/jouhou/1028723.html) へのリンクを追加する
=> 「第8回本部員会議 知事メッセージ（令和2年4月3日）」へのリンクを追加

components/SideNavigation.vue
- close #90 
- サイドバーのリンクを、感染症全体のページから、新型コロナウイルス感染症のページに変更
(左：変更前、右：変更後)
=> サイドバー 岩手県新型コロナウイルス情報のリンク先を変更

data/news.json
新型コロナウイルス感染症対策本部　第11回本部員会議　知事メッセージ（令和2年4月17日）
- close #148 
- 新型コロナウイルス感染症対策本部　第11回本部員会議　知事メッセージ（令和2年4月17日）
=> ニュース更新 20200421

.github/workflows/ogp_builder.yml
- close #157 
- ogp builder が走るのは master ブランチのみに変更
=> ogp builder が走るのは master ブランチのみに変更

components/SideNavigation.vue
=> 東京都YouTubeチャンネルの削除

data/news.json, pages/index.vue
=> index の card の並びを元に戻す

data/news.json
=> NEWS: 第14回会議の資料が公表された

pages/index.vue
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> index の card の並びを調整

components/cards/AntigenTestedNumberCard.vue, nuxt.config.ts, pages/cards/_card.vue
cards/antigen-tested-number-card
から
cards/number-of-antigen-tested
にURLを変更
- close #299
=> 抗原検査のcardのURLを変更

pages/index.vue
=> remove: disable ConfirmedCaseAttributesCard

data/news.json
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> 初の感染確認ニュース

components/DataTable.vue, data/data.json, utils/formatTable.ts
- close #370 
- 「通番」から「個別ページ」への外部リンクを設置
=> 「要請患者の属性」に「通番」から個別ページへのリンクを設置

data/news.json
第18回会議
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> update: news

layouts/default.vue
for google search console
- close #389 
- google-site-verification の meta タグを追加
=> add: google-site-verification

data_tools/google_sheets_to_data_json/generate_data_json.rb
- shebang の追加
- frozen_string_literal を利用
- コメント 整理
=> update: cli tools for data json

components/SideNavigation.vue
=> 岩手県版 v2 の作成 > 多言語対応をいったん取りやめる

data/news.json
=> 岩手県版 v2 の作成 > 「最新のお知らせ」を差し替える

components/SideNavigation.vue
=> 岩手県版 v2 の作成 > サイドナビゲーションを変更

.github/workflows/audit-staging.yml, CONTRIBUTING.md, FOR_DEVELOPERS.md, docs/en/CONTRIBUTING.md, docs/en/FOR_DEVELOPERS.md, docs/es/CONTRIBUTING.md, docs/es/FOR_DEVELOPERS.md, docs/fr/CONTRIBUTING.md, docs/fr/FOR_DEVELOPERS.md, docs/ko/CONTRIBUTING.md, docs/ko/FOR_DEVELOPERS.md, docs/pt_BR/CONTRIBUTING.md, docs/pt_BR/FOR_DEVELOPERS.md, docs/th/CONTRIBUTING.md, docs/th/FOR_DEVELOPERS.md, docs/vi/CONTRIBUTING.md, docs/vi/FOR_DEVELOPERS.md, docs/zh_CN/CONTRIBUTING.md, docs/zh_CN/FOR_DEVELOPERS.md, docs/zh_CN/README.md, docs/zh_TW/CONTRIBUTING.md, docs/zh_TW/FOR_DEVELOPERS.md
=> 岩手県版 v2 の作成 > ドキュメントの dev, stg 環境の URL を変更する

layouts/default.vue
- close #389 
- meta タグ に google-site-verification を設定
=> add: meta tag google-site-verification

data_tools/google_sheets_to_data_json/generate_data_json.rb
weekly_average_count
weekly_average_untracked_count
はfloat
=> fix: weekly_average_count はfloat

components/SideNavigation.vue, data/news.json, pages/about.vue
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> update: sidebar

.github/workflows/deploy.yml
=> delete Create GitHub release workflow

data_tools/google_sheets_to_data_json/generate_data_json.rb
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> update: output_patients

utils/formatTable.ts
patch for
https://github.com/MeditationDuck/covid19/pull/484
- #484 
- 東京版のマージで formatTable.ts の「通番」対応が抜けていたので戻す
=> add: 通番 type to formatTable.ts

utils/formatTable.ts
- #484 
- urlが空の場合は a href 無しで通番を表示する
=> urlが空の場合は a href 無しで通番を表示する

data/news.json
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> add: news スワロー号

data/news.json, utils/formatTable.ts
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> staging <= development

components/cards/UntrackedRateCard.vue
データが少ないのでグラフが綺麗な形にならないけど。
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> UntrackedRateCardの文言変更

components/DataTable.vue
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> 個別の退院を扱えないので、文章も非表示にする

.github/labeler.yml
data/*.json が更新されたら自動で data というlabelを付与する
- close #564
=> add: data labeler

data_tools/google_sheets_to_data_json/generate_data_json.rb
=> Update data cli tools

.github/labeler.yml, .github/workflows/pr-labeler.yml
- locales が変更されたら locales PRラベルをつける
- data が変更されたら data PRラベルをつける
=> update: add data label

components/SideNavigation.vue, components/SiteTopUpper.vue
- 岩手県 コロナ
- 岩手 コロナ
の検索順位の変動を観察する
- close #600
=> SEO: 「岩手」という単語を明示的に使う

components/ConfirmedCasesByMunicipalitiesTable.vue
=> ConfirmedCasesByMunicipalitiesTable にソートを実装する

layouts/default.vue, pages/cards/_card.vue, utils/formatDate.ts
- 日付の年月日表示変換
- descriptionの文言を data/*.json から組み立てる
- close #625 
- descriptionを data/*.json から動的に文言を組み立てる
=> meta name="description" を更新データに基づき、動的に変更する

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/ogp_builder.yml, .github/workflows/screenshot.yml, .github/workflows/staging.yml
=> fix: yarn run generate timezone env

layouts/default.vue, pages/cards/_card.vue
- #625 
- #626 
- #630 
- PCでは全て表示され、SPでは後半が省略されることを前提に文言を変更
=> update: descriptionの文言を追加

nuxt.config.ts, package.json, yarn.lock
- close #639 
- @nuxtjs/sitemap をインストール
- nuxt.config に sitemap の設定を追加
- 作成したいページ用の  sitemap.routes() を設定
=> sitemap.xml を生成する

nuxt.config.ts
- close #641 
- twitter:site と twitter:creator を削除
=> 東京のtwitterアカウントが残っているので削除

.github/workflows/update_json_build_app.yml
- #451 
https://github.com/suzuryo/covid19-iwate-data-bot
の workflow にて data/*.json を生成して、その生成したjsonをgh-pagesからcurlしてmasterにコミットする作戦
=> add: data update bot dispatch

.github/workflows/update_json_build_app.yml
=> add: auto push

.github/workflows/deploy.yml, .github/workflows/ogp_builder.yml, .github/workflows/staging.yml
- #451 
- #0
- update json の workflow が完了したら staging と production にデプロイする
=> update json の workflow が完了したらデプロイする

.github/workflows/deploy.yml, .github/workflows/ogp_builder.yml, .github/workflows/staging.yml, .github/workflows/update_json_build_app.yml
- #451 
- update json したら master は ogp_build して production deploy する
=> update json => ogp_build => production deploy

.github/workflows/update_json_build_app.yml
- close #0
- close #0
- #451 
- timezoneをJSTに設定
=> add: setup timezone

.github/workflows/deploy.yml, .github/workflows/ogp_builder.yml, .github/workflows/update_json_build_app.yml
=> cronで定時deployを試す

.github/workflows/ogp_builder.yml, .github/workflows/update_json_build_app.yml
- #451 
- ogp_builderはcronで実行しない
=> Add update json dispatch workflow

.github/workflows/deploy.yml
- #451 
- cron:  '30 */8 * * *' で production deploy する
=> production deploy cron:  '30 */8 * * *'

.github/workflows/deploy.yml
- #451 
- 10:30 UTC (19:30 JST)
- 12:30 UTC (21:30 JST)
- 15:30 UTC (00:30 JST)
- 22:30 UTC (07:30 JST)
に実行する
=> cronの実行タイミングの調整

.github/workflows/deploy.yml
- close #683 
- #640 
- デプロイが完了したら、Google に sitemap.xml を打つ workflow の処理を追加
=> デプロイしたらGoogleにsitemap.xmlをpingする

layouts/default.vue
COVID-19（新型コロナウイルス感染症）に関するお知らせに構造化データを追加する（ベータ版）
https://developers.google.com/search/docs/data-types/special-announcements
- close #687 
- [COVID-19（新型コロナウイルス感染症）に関するお知らせに構造化データを追加する（ベータ版）](https://developers.google.com/search/docs/data-types/special-announcements) に対応する
=> ld+jsonのSpecialAnnouncementな構造化データを追加

.github/workflows/check_broken_links.yml
- #692 
- suzuryo/covid19-iwate-data-bot の github actions から event dispatch する
=> add: check_broken_links event dispatch

.github/workflows/deploy.yml
- close #451 
- schedule で実行せずに、repository_dispatch の deploy_production を suzuryo/covid19-iwate-data-bot の schedule から呼ぶ
=> remove schedule / add dispatch deploy_production

layouts/default.vue
=> ld+jsonにBreadcrumbListを追加

.github/workflows/check_broken_links.yml
- close #716 
- github actions ruby 2.7.2
=> update: ruby 2.7.1 to 2.7.2

data/news.json
- close #737 
- 感染経路特定困難の文言をnewsに掲載
=> update: ニュース更新 (感染経路の推定が困難)

data/news.json
「海鮮季節料理おおいし」の利用者は連絡を
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> news: 海鮮季節料理おおいしの利用者は連絡を

.github/workflows/update_json.yml
- close #750 
- https://github.com/suzuryo/covid19-iwate-data-bot が Google Sheets 経由で定時生成する news.json を利用する
=> data bot が生成した news.json を利用する

components/cards/HospitalizedNumberCard.vue
- close #758 
- 「入院患者数」から「入院と宿泊療養の患者数」にタイトルを変更
=> HospitalizedNumberCardのタイトルを「入院と宿泊療養の患者数」に変更

ui-test/ogp_screenshot.py
- close #768 
- ?dummy というファイルを生成しない
=> OGP画像のアップロードエラーの解消

.github/workflows/ogp_builder.yml
- #769 
- data bot の update_json で OGP の作成を dispatch する
=> data bot の update_json で OGP を作成する

.github/workflows/ogp_builder.yml
- close #768 
- data bot で generate_ogp を dispatch する
=> update: generate_ogp dispatch type

.github/workflows/ogp_builder.yml
=> ogp生成はdata botから、またはmasterにpull_requestされたとき

auto-i18n/i18n_generator.py
=> data json に 退院 は含まれない

.github/workflows/ogp_builder.yml
=> ogpを生成するのは master ブランチのみに制限

.github/workflows/ogp_builder.yml
=> Update dispatch generate ogp

.github/workflows/ogp_builder.yml
- close #0
- close #0
- #768 
- #0
- xxxxxx
- xxx
=> ubuntu-latest の python3 -m http.server には -d オプションが無い？

.github/workflows/ogp_builder.yml
=> ubuntuでOGPを生成してみたが、やはりフォントがしょぼいのでmacosに戻す

.github/workflows/ogp_builder.yml
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> master <= staging

.github/workflows/ogp_builder.yml
=> ogp push to production

.github/workflows/ogp_builder.yml
=> ogp push to master

.github/workflows/ogp_builder.yml
=> OGP画像生成workflowの調整

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml, .github/workflows/on_push_to_dev_and_dispatch_from_googleSheetsMenu_development.yml
=> Refactor workflow

.github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml
=> 時間のかかるOGP生成をしないパターンのデプロイ

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
- close #768 
- コンフリクトの発生を抑えるため、developmentとmasterの両方にjsonをコミットする
=> googleSheetMenuWithoutOGP で development にも json をコミットする

components/ConfirmedCasesDetailsTable.vue
=> 死亡を退院等の子要素とする

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
- close #875 
- workflow の check_broken_links は update_json_development の後に実行する
=> check_broken_links は update_json_development の後に実行する

spec/feature/check_broken_links_spec.rb
=> check_broken_linksの print のタイミング変更

spec/feature/check_broken_links_spec.rb, spec/spec_helper.rb
=> add debug code

.github/workflows/on_pr_to_stage_audit-staging.yml
- close #812 
- https://github.com/tokyo-metropolitan-gov/covid19/pull/5737
- https://github.com/tokyo-metropolitan-gov/covid19/pull/5726
=> GitHub Actionsでset-envが非推奨になったため修正

components/SideNavigation.vue
- #892 
```1355570 dist/_nuxt/app.js```
- https://github.com/tokyo-metropolitan-gov/covid19/pull/5722/commits/35fad2cb1face715747dda44fd6548d68707d3ef
- img への height/width の追加
- 利用していない LanguageSelector を読み込まない
=> 利用していないLanguageSelectorを削除

layouts/default.vue, nuxt.config.ts, package.json, yarn.lock
https://github.com/tokyo-metropolitan-gov/covid19/pull/5720
https://github.com/tokyo-metropolitan-gov/covid19/pull/5720/commits/c2206cafd2eebcc9bc90030309364bffd5d142fd
- close #894
=> perf: Web font の読み込みを最適化する

components/DataTable.vue, components/ExternalLink.vue, utils/formatTable.ts
=> DataTableに記者会見のyoutubeのリンクを含める

components/DataTable.vue, utils/formatTable.ts
=> quickfix: 陽性確定日が不明になってしまう

components/DataTable.vue, utils/formatTable.ts
- close #924 
- 確定日が全て同じ日付になっている
=> quickfix: 確定日が同じ日になっている

nuxt.config.ts
- #953 
- 一時的に 'nuxt-purgecss' を無効にする
=> hotfix: nuxt-purgecssを一時的に無効にする

nuxt.config.ts
- #639
- sitemapの重複を削除
- sitemapに追加されていなかったuntrackを追加
=> sitemapの追加・削除

components/DataViewTable.vue, components/HospitalizedTimeStackedBarChart.vue
- close #763 
- データテーブルに、入院と宿泊療養の合計表示する
- データテーブルの header .text-end を効かせる
=> Add hospitalized number card daily total

.github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- close #813 
- ogpの生成をしてコミットしてからビルドする
=> fix: generate_ogp => build_and_deploy

.github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
すべて macos-latest を使った一つのjobで完結させる
- #768
- macos-latest で OGPの生成をやるんだから、その流れで production build & producion deploy もやってしまう
=> googleSheetMenu_master を改良

.github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- #768 
- actions/cache@v2 を追加
=> googleSheetMenu_master に cache を導入

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
- close #985 
- Cybertrust Japan Public CA G3 の中間証明書をインストールして、www.mext.go.jp の ssl cert の verify に成功するようにする
=> Improve workflow

.github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- #768
- #979
- generateは1回しかせず、生成されたOGPはdistに直接コピーしてgh-pagesする
=> generateは1回しかせず、生成されたOGPは直接distに入れる

.github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
- #768
- #979
- node_modulesもcacheする
- googleSheetMenu_master が問題なく動いたので googleSheetMenuWithoutOGP_master と googleSheetMenu_development にも反映させる
=> Improve workflow development

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
- #998 
- googleSheetMenu_development の調整で外れていた git commit & git push を追加
=> add git push action to googleSheetMenu_development

package.json, yarn.lock
=> update packages 20201211

.github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- #768 
- OGP生成でスタックすることがあるので、```python -m http.server``` から ```ruby -run -ehttpd``` に変えてみる
=> ogp生成でスタックすることがあるので、webrickに変更してみる

components/DataTable.vue, components/MixedBarAndLineChart.vue, components/MonitoringConfirmedCasesChart.vue, components/MonitoringConsultationDeskReportChart.vue, components/SevereCaseBarChart.vue, components/TimeBarChart.vue, components/cards/MonitoringConsultationDeskReportsNumberCard.vue, components/cards/TelephoneAdvisoryReportsNumberCard.vue
=> 利用していないOpenDataLinkとprops :url を削除

.github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml, nuxt.config.ts, ui-test/ogp_screenshot.py
- #1016 
- #805 
- workflowの調整
- OGP生成の調整
- sitemap生成の調整
=> Update workflow 20201214

nuxt.config.dev.ts, package.json
- close #1039 
- 本番用と開発用に nuxt.config ファイルを分ける
=> 開発用の nuxt.config ファイルを追加する

utils/formatTable.ts
- close #1052 
- data.json.patients の サイズを小さくするため key の名前を変更
=> Change patients json key

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
- #985 
- 中間証明書のインストールで openssl verify する
=> 中間証明書のインストールで openssl verify する

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
=> 1行で実行してverifyの失敗を検出する

assets/global.scss, assets/variables.scss, components/DataViewDataSetPanel.vue, nuxt-i18n.config.ts, nuxt.config.dev.ts, nuxt.config.ts, package.json, yarn.lock
- close #1090 
- webfontを利用しない
- Windowsは游ゴシックで表示する
=> Windowsは游ゴシックで表示する

.github/workflows/on_pr_to_dev_rspec.yml, Gemfile, Gemfile.lock, components/cards/ConfirmedCasesAttributesCard.vue, components/cards/ConfirmedCasesByMunicipalitiesCard.vue, components/cards/ConfirmedCasesDetailsCard.vue, components/cards/ConfirmedCasesNumberCard.vue, components/cards/HospitalizedNumberCard.vue, components/cards/MonitoringConfirmedCasesNumberCard.vue, components/cards/MonitoringConsultationDeskReportsNumberCard.vue, components/cards/PositiveNumberByDevelopedDateCard.vue, components/cards/PositiveNumberByDiagnosedDateCard.vue, components/cards/PositiveRateCard.vue, components/cards/SevereCaseCard.vue, components/cards/TelephoneAdvisoryReportsNumberCard.vue, components/cards/TestedNumberCard.vue, components/cards/UntrackedRateCard.vue, spec/feature/index_ConfirmedCasesAttributesCard_spec.rb, spec/feature/index_ConfirmedCasesByMunicipalitiesCard_spec.rb, spec/feature/index_ConfirmedCasesDetailsCard_spec.rb, spec/feature/index_ConfirmedCasesNumberCard_spec.rb, spec/feature/index_HospitalizedNumberCard_spec.rb, spec/feature/index_MonitoringConfirmedCasesNumberCard_spec.rb, spec/feature/index_MonitoringConsultationDeskReportsNumberCard_spec.rb, spec/feature/index_PositiveRateCard_spec.rb, spec/feature/index_TelephoneAdvisoryReportsNumberCard_spec.rb, spec/feature/index_TestedNumberCard_spec.rb, spec/feature/index_UntrackedRateCard_spec.rb, spec/feature/index_spec.rb, spec/spec_helper.rb
- #1105 
- index に対する表示項目と動作のテスト
=> Add rspec feature tests for index

layouts/default.vue, package.json, types/window-workbox.d.ts, yarn.lock
- close #1112 (対応方法 3 で実装)
- #1010 
- PWAは維持したまま、ServiceWorker (sw.js) が更新されたら、ページを強制リロードして新しいchunkを取得する
=> sw.js が 更新されたら ページを強制的にリロードする

package.json, yarn.lock
=> Update packages 20201230

spec/feature/index_ConfirmedCasesAttributesCard_spec.rb, spec/feature/index_ConfirmedCasesByMunicipalitiesCard_spec.rb, spec/feature/index_ConfirmedCasesNumberCard_spec.rb, spec/feature/index_HospitalizedNumberCard_spec.rb, spec/feature/index_MonitoringConfirmedCasesNumberCard_spec.rb, spec/feature/index_MonitoringConsultationDeskReportsNumberCard_spec.rb, spec/feature/index_PositiveRateCard_spec.rb, spec/feature/index_TelephoneAdvisoryReportsNumberCard_spec.rb, spec/feature/index_TestedNumberCard_spec.rb, spec/feature/index_UntrackedRateCard_spec.rb
- #1105 
- month/day は no zero padding でテストする
=> fix: Date.strftime non zero padding month/day

.github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- close #1121 
- workflow で self_disclosures.json のダウンロード
=> update workflow for self_disclosures.json

layouts/default.vue
- close #1112 
- PWAの時だけリロードする
=> PWAの時だけリロードする

layouts/default.vue, nuxt.config.dev.ts, nuxt.config.ts, package.json, types/window-workbox.d.ts, yarn.lock
=> workboxを使ったpwaのsw.jsをやめる

spec/feature/index_HospitalizedNumberCard_spec.rb, spec/feature/index_MonitoringConfirmedCasesNumberCard_spec.rb, spec/feature/index_PositiveRateCard_spec.rb, spec/feature/index_TelephoneAdvisoryReportsNumberCard_spec.rb, spec/feature/index_TestedNumberCard_spec.rb, spec/feature/index_UntrackedRateCard_spec.rb
- #1105 
- v-expansion-panelの開閉のタイミングによってfailしてる？
=> expansionのタイミングによりfailsする場合があるので、とりあえずsleepで回避する

auto-i18n/i18n_generator.py
- #1148 
- i18n_generator への追加忘れ
=> add WhatsNew to ignore list, i18n_generator

assets/locales/en.json, pages/flow.vue
- #1031 
- ja以外の時に、enページへのリンクボタンを表示する
=> add en button to flow

components/CardsLazyRow.vue, components/cards/ConfirmedCasesAttributesCard.vue, components/cards/ConfirmedCasesByMunicipalitiesCard.vue, components/cards/ConfirmedCasesDetailsCard.vue, components/cards/ConfirmedCasesNumberCard.vue, components/cards/HospitalizedNumberCard.vue, components/cards/MonitoringConfirmedCasesNumberCard.vue, components/cards/MonitoringConsultationDeskReportsNumberCard.vue, components/cards/PositiveNumberByDevelopedDateCard.vue, components/cards/PositiveNumberByDiagnosedDateCard.vue, components/cards/PositiveRateCard.vue, components/cards/SelfDisclosuresCard.vue, components/cards/SevereCaseCard.vue, components/cards/TelephoneAdvisoryReportsNumberCard.vue, components/cards/TestedNumberCard.vue, components/cards/UntrackedRateCard.vue, components/cards/WhatsNewCard.vue, pages/cards/_card.vue
- close #1170 
- 集合表示の時はmd=6で、単品表示の時はmd=12にする
=> indexで表示するときはmd=6で、cardで表示するときはmd=12でレイアウトする

components/CardsTab.vue
- close #1203 
- activeなtabをハイライトする
=> アクティブなタブの方をハイライトする

spec/feature/index_PositiveRateCard_spec.rb
=> positive_rate を toFixed(1) する

.github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml, .github/workflows/on_pr_to_dev_rspec.yml, .github/workflows/on_pr_to_stage_audit-staging.yml, .github/workflows/on_push_to_stage_staging.yml
=> update setup-node 14.15.4

spec/lib/PositiveRateCard.rb
- #1196
- jsのtoFixedとrubyのroundの挙動の違いを吸収
=> toFixedを使って桁数を調整する

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_pr_to_dev_rspec.yml
=> ractions/setup-ruby ではなく ruby/setup-ruby を使う

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_pr_to_dev_rspec.yml
=> bundle install は ruby/setup-ruby の bundler-cache: true で実行される

.github/workflows/on_pr_to_dev_reviewdog.yml, components/MonitoringConfirmedCasesChart.vue
=> 1週間あたりの対10万人をちゃんと計算する

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_pr_to_dev_rspec.yml
=> add parallels spec file path

assets/locales/en.json, assets/locales/ja.json, components/ConfirmedCasesDetailsTable.vue, components/cards/ConfirmedCasesDetailsCard.vue, pages/cards/_card.vue, spec/feature/cards/cards_ConfirmedCasesDetailsCard_spec.rb, spec/feature/index/index_ConfirmedCasesDetailsCard_spec.rb, spec/lib/BreadCrumbs.rb, spec/lib/ConfirmedCasesDetailsCard.rb, spec/spec_helper.rb
=> update locales / rspec ConfirmedCasesDetailsCard

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_pr_to_dev_rspec.yml, .gitignore, components/LanguageSelector.vue, spec/feature/index/index_LanguageSelector_spec.rb, spec/feature/index/index_SideNavigation_spec.rb, spec/feature/index/index_h1h2_spec.rb, spec/spec_helper.rb
- #1105 
- #1143 
- render_lazy_contents で 実際にlazyで読み込んだDOMの構築完了を待つ
=> render_lazy_contentsの改良

spec/feature/index/index_SideNavigation_spec.rb
- #1105 
- タイミングによりfailするのでsleepで回避
=> rspec: timing sleep

.github/workflows/on_pr_from_renovate_rspec.yml
=> fix renovate actions

.github/workflows/on_pr_from_renovate_rspec.yml
- /renovate/** に push されたときにrspecする
=> renovate rspec

assets/global.scss, components/ScrollableChart.vue
=> Add print css

.github/workflows/on_push_to_dev_rspec.yml
- #1105 
- development に push した場合(データ更新など)
- development に pull_request した場合(コード修正など)
=> push_to_dev と pull_to_dev の rspec を追加

components/AppLink.vue, components/DataView.vue, components/NotesExpansionPanel.vue, components/SideNavigation.vue, nuxt.config.ts, plugins/axe.ts, yarn.lock
- close #1375 
- close #1376 
- eslint の warning を解消
- axe は development の時だけ利用する
=> Fix eslint warning

components/ConfirmedCasesDetailsTable.vue, spec/lib/ConfirmedCasesDetailsCard.rb
- close #1409 
- #1079 
- 割合の表示の追加
- 関連するテストを追加
=> 陽性者数に対する退院の割合を表示する

components/ConfirmedCasesByMunicipalitiesTable.vue, components/DataTable.vue, components/DataViewDataSetPanel.vue, components/HospitalizedTimeStackedBarChart.vue, components/MixedBarAndLineChart.vue, components/MonitoringConfirmedCasesChart.vue, components/MonitoringConsultationDeskReportChart.vue, components/PositiveRateMixedChart.vue, components/SevereCaseBarChart.vue, components/TimeBarChart.vue, components/TimeStackedBarChart.vue, components/UntrackedRateMixedChart.vue, components/WhatsNew.vue, components/cards/ConfirmedCasesDetailsCard.vue, spec/lib/ConfirmedCasesAttributesCard.rb, spec/lib/ConfirmedCasesByMunicipalitiesCard.rb, spec/lib/ConfirmedCasesDetailsCard.rb, spec/lib/ConfirmedCasesNumberCard.rb, spec/lib/HospitalizedNumberCard.rb, spec/lib/MonitoringConfirmedCasesNumberCard.rb, spec/lib/MonitoringConsultationDeskReportsNumberCard.rb, spec/lib/PositiveRateCard.rb, spec/lib/SelfDisclosuresCard.rb, spec/lib/TelephoneAdvisoryReportsNumberCard.rb, spec/lib/TestedNumberCard.rb, spec/lib/UntrackedRateCard.rb, spec/lib/WhatsNewCard.rb
- close #1414 
- #1210 
- data-set-panelのh3にapp-linkで個別cardへのリンクの設置
- specの追加
=> data-set-panelのh3にapp-linkで個別cardへのリンクの設置

components/DataViewShare.vue, components/HospitalizedTimeStackedBarChart.vue, components/PositiveRateMixedChart.vue, components/TimeBarChart.vue, components/TimeStackedBarChart.vue
=> 不要なthisのエイリアスを削除する

components/ConfirmedCasesDetailsTable.vue, spec/lib/ConfirmedCasesDetailsCard.rb
- #1409 
- Math.round だと 90.0 じゃなくて 90 になるので
=> Math.round から toFixed に変更

components/StaticInfo.vue, spec/lib/SiteTopUpper.rb
- close #1439 
- StaticInfoの内部をAppLinkで実装
- 関連するspec
=> StaticInfoをAppLinkで実装

pages/cards/_card.vue
- #1210 
- breadcrumbのデータをhrefからtoに変更してnuxt-link(再読み込み無し)のように動作するのを期待
=> change breadcrumb data href => to

components/CardsMonitoring.vue, components/CardsReference.vue, spec/feature/index/index_MonitoringConsultationDeskReportsNumberCard_spec.rb, spec/feature/index/index_TelephoneAdvisoryReportsNumberCard_spec.rb
=> 電話相談を２番目のタブの中に移動する

Gemfile.lock, spec/feature/check_broken_links_spec.rb, spec/feature/check_unregister_serviceworker_spec.rb
- #1105 
- 利用していないrequireを整理
- bundle update
=> 利用していないrequireを整理

components/WhatsNew.vue, components/cards/SelfDisclosuresCard.vue, spec/lib/SelfDisclosuresCard.rb
=> add self_disclosure_form

spec/lib/ConfirmedCasesDetailsCard.rb
=> DetailsCardの前日差 spec

components/WhatsNew.vue
- #1523 
- `items-per-page="200"` に変更して暫定的に対処
=> hotfix: データが100を超えていたので暫定的に200に増やして表示切れ対処

components/cards/WeeklyMapCard.vue
- #1559 
- data() の中でデータ初期化しないとmountするたびにcountがどんどん増えてた
=> hotfix: bugfix data() の中でデータ初期化

components/WeeklyMap.vue, components/cards/WeeklyMapCard.vue
- #1559 
- 岩手県全域の場合は1週間の陽性件数を表示する
- 個別市町村の場合は管内を含めた数を表示する
=> 岩手県全域の場合は陽性件数を表示する

components/WeeklyMap.vue, components/cards/WeeklyMapCard.vue
- #1570
- mouseenter でもdataSetPanelを更新する(PC向け)
- click でもdataSetPanelを更新する(スマホ向け)
=> Fix city map mouseover

components/SideNavigation.vue, spec/feature/index/index_SideNavigation_spec.rb
- close #1582 
- 新しいURLに変更
- specの追加
=> SideNavigation の 新型コロナウイルス感染症対策本部 の url を更新

utils/colors.ts
=> 調整中の色を グレー に変更

components/WeeklyMap.vue
- #1559 
- カーソルが市町村の上なら、市町村の情報を表示
- カーソルが市町村の上から離れたら、岩手県全域の情報を表示
=> カーソルが市町村から離れたら岩手県全域のdatasetpanelを表示する

assets/locales/en.json, spec/lib/ConfirmedCasesByMunicipalitiesCard.rb
- close #1606 
- en の ruby 削除もれ fix
- table > thead > tr > th に関する spec の追加
=> en の ruby 削除もれ fix / table > thead > tr > th に関する spec の追加

nuxt.config.dev.ts, nuxt.config.ts, package.json, yarn.lock
=> add nuxt-gtm

spec/feature/cards/cards_PositiveRateCard_spec.rb, spec/feature/cards/cards_SelfDisclosuresCard_spec.rb, spec/feature/cards/cards_WeeklyMapCard_spec.rb, spec/feature/index/index_PositiveRateCard_spec.rb, spec/feature/index/index_SelfDisclosuresCard_spec.rb, spec/lib/PositiveRateCard.rb, spec/lib/SelfDisclosuresCard.rb
- #1105 
- SelfDisclosure の 多言語 テスト
- PositiveRate の 多言語 テスト
=> SelfDisclosure / PositiveRate の 多言語 テスト

components/WeeklyMap.vue
- close #1638 
- 県全体がpngに収まるように調整
=> OGP生成時のWeeklyMapのサイズとポジションを調整し

components/SideNavigation.vue, spec/feature/index/index_SideNavigation_spec.rb
- close #1653 
- CopyrightのYearを動的に生成する
=> Copyrightの2020を2021に変更

FOR_DEVELOPERS.md, docs/en/FOR_DEVELOPERS.md
- #20
- README.md / docs のメンテナンス
=> README.md / docs のメンテナンス / 英語と日本語が入れ替わってた

spec/feature/check_broken_links_spec.rb
=> add timeout to Typhoeus

spec/feature/check_broken_links_spec.rb
- close #1678 
- timeout 3 to 10
=> update timeout 3 to 10

ui-test/ogp_composite_weekly_map.js
- #1681 
- github action でエラーが発生していたため修正
=> fix: ogp_composite_weekly_map.js

README.md, docs/en/README.md
- close #1681 
- README.md の OGP画像のURLを本番サイトを参照
=> update README.md ogp

.github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- close #1681 
- actions-gh-pages 用に ogp.png を dist/ にコピーする
=> update workflow ogp.png copy

.github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml, .github/workflows/on_pr_from_renovate_rspec.yml, .github/workflows/on_pr_to_dev_rspec.yml, .github/workflows/on_push_to_dev_rspec.yml
=> node 14.17.0

assets/variables.scss
=> 配色のコントラストを少し高くする

assets/variables.scss
=> more contrast

components/HospitalizedTimeStackedBarChart.vue, components/SideNavigation.vue, components/TimeStackedBarChart.vue, components/cards/ConfirmedCasesAttributesCard.vue, layouts/default.vue, nuxt.config.dev.ts, nuxt.config.ts, package.json, pages/flow.vue, yarn.lock
- close #1718 
- #1310 
- 2つのボタンと、関連するスクロール制御等を削除する
- 印刷した時に大事な部分がA4縦の1ページ目に全て収まるようになった。
- yarn lint --fix
=> 2つのボタンと、関連するスクロール制御等を削除する

nuxt.config.dev.ts, nuxt.config.ts
- close #1722 
- vue-meta で charset を出さない
=> meta charset が 2つ出力されている

nuxt.config.dev.ts, nuxt.config.ts, spec/feature/cards/cards_ConfirmedCasesAttributesCard_spec.rb, spec/feature/cards/cards_ConfirmedCasesByMunicipalitiesCard_spec.rb, spec/feature/cards/cards_ConfirmedCasesDetailsCard_spec.rb, spec/feature/cards/cards_ConfirmedCasesNumberCard_spec.rb, spec/feature/cards/cards_HospitalizedNumberCard_spec.rb, spec/feature/cards/cards_MonitoringConfirmedCasesNumberCard_spec.rb, spec/feature/cards/cards_PositiveRateCard_spec.rb, spec/feature/cards/cards_SelfDisclosuresCard_spec.rb, spec/feature/cards/cards_TestedNumberCard_spec.rb, spec/feature/cards/cards_UntrackedRateCard_spec.rb, spec/feature/cards/cards_WeeklyMapCard_spec.rb, spec/feature/cards/cards_WhatsNewCard_spec.rb, spec/feature/check_broken_links_spec.rb, spec/feature/page/page_print_flow_spec.rb, spec/feature/page/page_vaccine_spec.rb, spec/lib/ConfirmedCasesAttributesCard.rb, spec/lib/ConfirmedCasesByMunicipalitiesCard.rb, spec/lib/ConfirmedCasesDetailsCard.rb, spec/lib/ConfirmedCasesNumberCard.rb, spec/lib/HospitalizedNumberCard.rb, spec/lib/MonitoringConfirmedCasesNumberCard.rb, spec/lib/PositiveRateCard.rb, spec/lib/SelfDisclosuresCard.rb, spec/lib/SiteTopUpper.rb, spec/lib/TestedNumberCard.rb, spec/lib/UntrackedRateCard.rb, spec/lib/WeeklyMapCard.rb, spec/lib/WhatsNewCard.rb
=> Nuxt link trailing slash

spec/lib/SelfDisclosuresCard.rb
- #1105 
- SelfDiscosures の en/ja 対応の修正
=> rspec SelfDiscosures の en/ja 対応の修正

nuxt.config.dev.ts, nuxt.config.ts
- close #1745 
- #640
- sitemap.xmlを多言語対応で書き出す
=> sitemap.xml を 多言語対応する

Gemfile.lock
- close #1757 
- bundle update
=> bundle update nokogiri (1.11.3) -> nokogiri (1.11.4)

components/DataTable.vue
=> v-data-table の a:visited を指定

assets/variables.scss, components/DataTable.vue, components/DataView.vue
=> update font, link settings

components/HospitalCapacity.vue, components/HotelCapacity.vue
- close #1772 
- #1788 
- 枠の中に収まるようにフォント指定
=> 枠の中に収まるようにフォント指定

components/cards/WeeklyMapCard.vue
- #1559
- 居住地の値が、市町村と保健所管内に存在しない項目の場合、エラーが発生する場合があったので対処
=> 居住地と保健所管内とその他の判定ロジックを改良

components/CardsMonitoring.vue, components/MonitoringConfirmedCasesChartPer100k.vue, components/cards/MonitoringConfirmedCasesNumberPer100kCard.vue, pages/cards/_card.vue
=> 盛岡市の直近1週間の新規患者数（対人口10万人）Card

components/MonitoringConfirmedCasesChartPer100k.vue
=> Monitoring number of confirmed cases per 100k 2

components/_shared/PageHeader.vue, components/index/SiteTopUpper.vue, pages/about.vue, pages/flow.vue, pages/index.vue, pages/vaccine.vue, pages/worker.vue, spec/feature/index/index_LanguageSelector_spec.rb, spec/feature/index/index_PageHeader_spec.rb, spec/feature/index/index_SideNavigation_spec.rb, spec/feature/index/index_h1h2_spec.rb, spec/feature/page/page_vaccine_spec.rb, spec/lib/PageHeader.rb, spec/lib/SiteTopUpper.rb
- close #1851 
- PageHeaderをindexから使う
- DOMの変更が発生したのでrspecも変更
=> PageHeaderをindexから使う

spec/lib/MonitoringConfirmedCasesNumberCard.rb
- #1105 
- 小数点の .toFixed(1) の扱い
=> rspec: 小数点の .toFixed(1) の扱い

spec/feature/page/page_print_flow_spec.rb
- #1105 
- github actions 環境でたまにfailするテストをコメントアウト
=> github actions 環境でたまにfailするテストをコメントアウト

components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue
=> 岩手県の人口の修正漏れ

.github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- #1882 
- netlify へのデプロイは nwtgck/actions-netlify@v1.2 を使う
=> use nwtgck/actions-netlify@v1.2 to netlify deploy

.github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- #1882
- Deploy Preview でのデプロイできたので、production-deploy を true にして本番投入する
=> set production-deploy true

package.json, yarn.lock
- close #1909 
- vue 2.6.14 にアップデート
=> vue を 2.6.14 にアップデート yarn.lock の再生成

spec/lib/MonitoringConfirmedCasesNumberPer100kCard.rb, spec/lib/WeeklyMapCard.rb
- #1105 
- data.jsonのpatientsが増えないことに対応するrspec
=> data.jsonのpatientsが増えないパターンに対応

components/index/_shared/DataView/Share.vue
=> fix: focus share button on close

.devcontainer/devcontainer.json
=> chore: remove appPort

components/index/_shared/DataViewTable.vue, components/index/_shared/ScrollableChart.vue
=> fix: focus to charts and tables

components/_shared/SideNavigation.vue, layouts/default.vue
=> モバイルレイアウト時のメニューのフォーカス不具合を修正

components/index/CardsMonitoring/ConfirmedCasesAttributes/DataTable.vue
=> fix: remove aria-readonly of readonly input

components/_shared/SideNavigation.vue, spec/feature/index/index_SideNavigation_spec.rb
=> サイドメニュー内のソーシャルメディアへのリンクを ul, li タグでマークアップする

components/_shared/AppLink.vue, components/index/CardsMonitoring/ConfirmedCasesAttributes/DataTable.vue, components/index/CardsMonitoring/HospitalizedNumber/Chart.vue, components/index/CardsReference/SelfDisclosures/Card.vue, components/index/CardsReference/SelfDisclosures/Table.vue, components/index/CardsReference/WhatsNew/Card.vue, components/index/CardsReference/WhatsNew/Table.vue, components/index/_shared/DataViewTable.vue, spec/lib/ConfirmedCasesAttributesCard.rb, spec/lib/ConfirmedCasesNumberCard.rb, spec/lib/HospitalizedNumberCard.rb, spec/lib/MonitoringConfirmedCasesNumberCard.rb, spec/lib/PositiveRateCard.rb, spec/lib/SelfDisclosuresCard.rb, spec/lib/TestedNumberCard.rb, spec/lib/UntrackedRateCard.rb, spec/lib/WhatsNewCard.rb
- #1953 
- 日付関係に対して time の datetime を指定する
=> 日付を扱っている部分にtimeタグを使う

assets/locales/en.json
=> fix: typo tokyo => iwate

ui-test/ogp_screenshot.py
=> fix ogp script

components/index/CardsMonitoring/EffectiveReproductionNumber/Card.vue, components/index/CardsMonitoring/EffectiveReproductionNumber/Chart.vue, spec/lib/EffectiveReproductionNumberCard.rb
=> 実効再生産数(推定値)の値を小数第2位まで表示する

components/index/CardsMonitoring.vue, plugins/vue-chart.ts
=> 先頭に計算量の多いコンポーネントを置くとLighthouseのPerformanceが低下するので軽いのを上に

plugins/vue-chart.ts
- #1994 
- https://github.com/MeditationDuck/covid19/pull/2005/commits/9a59f8b4be87e4215d84da9c6ecb362a4dc397c5
- BUGFIX
=> setTimeou() を外したら annotation が描画されなくなったので復元

components/index/CardsMonitoring/ConfirmedCasesAttributes/DataTable.vue, utils/formatTable.ts
- #892
- VideoIDだけdata.jsonに入ってるので、記者会見のYouTubeのURLはそれから生成する
=> 記者会見のYouTubeのURLはVideoIDだけdata.jsonに入ってるので、それから生成する

components/index/CardsMonitoring/ConfirmedCasesAttributes/Card.vue, components/index/CardsMonitoring/ConfirmedCasesAttributes/DataTable.vue, components/index/CardsMonitoring/TestedNumber/Card.vue, utils/formatTable.ts
=> dataのlabelになる日付はiso8601じゃなくて '%Y-%m-%d' にする

components/index/CardsMonitoring.vue, components/index/CardsMonitoring/ConfirmedCasesAttributes/DataTable.vue, nuxt.config.dev.ts
=> babel-preset の target は ie11 にする

components/index/SiteTopUpper.vue, spec/lib/SiteTopUpper.rb
- close #2041 
- static-infoをlazyでなくする
=> static-infoをlazyでなくする

components/index/CardsTab.vue
=> v-tab の v-icon を削除する変更

layouts/default.vue
=> ld+jsonのnameの文言を修正

nuxt-i18n.config.ts
=> nuxti18n options に baseurl を設定

package.json, yarn.lock
=> ts-loader 8.3.0 にダウングレード

spec/lib/PositiveRateCard.rb
=> rspec: 2021/07/23 が 検査件数より陽性件数の方が多い

components/index/_shared/DataView.vue
=> DataView-Footer のリンクを AppLink で実装する

components/index/CardsMonitoring/MonitoringConfirmedCasesNumberPer100k/Card.vue, spec/lib/MonitoringConfirmedCasesNumberPer100kCard.rb
=> 人口10万人あたりの初期選択肢を岩手県全域に設定

components/index/CardsMonitoring/ConfirmedCasesAttributes/DataTable.vue
=> tableのcssを微調整

spec/lib/WeeklyMapCard.rb
- close #2136 
- 滞在地に基づいたrspecに変更
=> 滞在地主義に対応したrspecに変更

ui-test/ogp_screenshot.py
=> RestaurantCardのogp生成

components/index/CardsIwateNinshou/Restaurant/Card.vue, nuxt.config.dev.ts, nuxt.config.ts, pages/cards/_card.vue, ui-test/ogp_screenshot.py
- close #2157 
- restaurant-mapのogp生成を改良
=> restaurant-mapのogp生成を改良

components/index/CardsMonitoring/WeeklyMap/Iwate.vue
=> 地図の色分けの計算式を単純化

components/index/CardsMonitoring/HospitalizedNumber/Chart.vue
- #1752
- #2161 
- BUGFIX: HospitalizedNumberCardのグラフの色分を修正
=> HospitalizedNumberCardのグラフの色分を修正

components/index/CardsMonitoring/EffectiveReproductionNumber/Chart.vue, components/index/CardsMonitoring/HospitalizedNumber/Chart.vue, components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue, components/index/CardsMonitoring/MonitoringConfirmedCasesNumberPer100k/Chart.vue, components/index/CardsMonitoring/PositiveRate/Chart.vue, components/index/CardsMonitoring/UntrackedRate/Chart.vue, components/index/_shared/TimeBarChart.vue, components/index/_shared/TimeStackedBarChart.vue
- close #2220 
- xAxes の day を削除する実装
=> グラフのxAxesからdayを削除

spec/lib/WeeklyMapCard.rb
- #2272 
- タイミングで？failsするのでコメントアウト
=> タイミングで？failsするのでコメントアウト

components/index/CardsMonitoring/WeeklyMap/Iwate.vue, spec/lib/WeeklyMapCard.rb
- #2272 
- #2276 
- weekly_mapをid実装に戻す
=> WeeklyMapを元の実装に戻す

spec/lib/WeeklyMapCard.rb
=> タイミングで？failsするのでsleepしてみる

spec/lib/WeeklyMapCard.rb
=> 市町村のsvgの挙動確認はスキップする

components/index/CardsMonitoring/HospitalCapacity/Beds.vue, components/index/CardsMonitoring/HotelCapacity/Beds.vue, spec/lib/HospitalCapacityCard.rb, spec/lib/HotelCapacityCard.rb
=> #2356 add bed num

components/_shared/SideNavigation.vue, components/_shared/SideNavigation/MenuList.vue, components/index/CardsMonitoring/AgeGroup/Card.vue, components/index/CardsMonitoring/AgeGroup/Chart.vue, components/index/CardsMonitoring/EffectiveReproductionNumber/Card.vue, components/index/CardsMonitoring/EffectiveReproductionNumber/Chart.vue, components/index/CardsMonitoring/HospitalizedNumber/Chart.vue, components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue, components/index/CardsMonitoring/MonitoringConfirmedCasesNumberPer100k/Card.vue, components/index/CardsMonitoring/MonitoringConfirmedCasesNumberPer100k/Chart.vue, components/index/CardsMonitoring/PositiveRate/Chart.vue, components/index/CardsMonitoring/UntrackedRate/Chart.vue, components/index/_shared/DataView.vue, components/index/_shared/DataViewTable.vue, components/index/_shared/ScrollableChart.vue, components/index/_shared/TimeStackedBarChart.vue, layouts/default.vue, layouts/print.vue, pages/about.vue, pages/index.vue, pages/vaccine.vue, pages/worker.vue, plugins/vue-chart.ts, types/weekly-map.d.ts
- close #2363 
- Type-Only Imports を使う
=> type only importsを使う

components/index/CardsMonitoring/AgeGroup/Chart.vue, components/index/CardsMonitoring/EffectiveReproductionNumber/Chart.vue, components/index/CardsMonitoring/HospitalizedNumber/Chart.vue, components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue, components/index/CardsMonitoring/MonitoringConfirmedCasesNumberPer100k/Chart.vue, components/index/CardsMonitoring/PositiveRate/Chart.vue, components/index/CardsMonitoring/UntrackedRate/Chart.vue, components/index/_shared/TimeBarChart.vue, components/index/_shared/TimeStackedBarChart.vue
=> グラフ目盛りのfontColorを#808080から#707070に変更

.github/workflows/on_pr_to_stage_audit-staging.yml
=> actions/github-script の v5 の breaking change に対応

pages/vaccine.vue
=> 盛岡市のHPがリニューアルされて、既存URLが404になった

pages/vaccine.vue
=> 盛岡市の集団接種に岩手大学を追加

pages/flow.vue
=> 診療・検査医療機関の一覧 のPDFのURLが変更

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_pr_from_renovate_rspec.yml, .github/workflows/on_pr_to_dev_rspec.yml, .github/workflows/on_push_to_dev_rspec.yml, spec/spec_helper.rb
- #1105 
- WARN Selenium [DEPRECATION] [:browser_options] に対応
- github actions でエラーが続いているので parallel_rspec ではなく 素の rspec で実行してみる
=> rspec : WARN Selenium [DEPRECATION] [:browser_options] に対応

pages/flow.vue
=> 診療検査医療機関一覧PDF更新

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_pr_from_renovate_rspec.yml, .github/workflows/on_pr_to_dev_rspec.yml, .github/workflows/on_push_to_dev_rspec.yml
- #2489 
- github actionsでのrspecが失敗するので、実行するspec数を減らす
=> rspecでテストする項目を減らす

pages/flow.vue
=> 診療医療機関のPDFを更新

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml, pages/flow.vue, utils/urls.ts
- close #2533 
- 診療医療機関一覧pdfをGoogleSheetsから入力を実装
=> 診療医療機関一覧pdfをGoogleSheetsから入力

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- close #2539 
- master から 直接取得する
- `peaceiris/actions-gh-pages` の仕様が変わった？感じで取得タイミングの問題が出てる？
=> peaceiris/actions-gh-pages の仕様が変わった気がするので、masterから直接取ってくる

components/index/CardsFeatured.vue, components/index/CardsMonitoring.vue, components/index/CardsReference.vue
=> Cardのコンポーネントをdynamic importする

components/index/CardsFeatured.vue, components/index/CardsMonitoring.vue, components/index/CardsReference.vue
=> Revert "Cardのコンポーネントをdynamic importする"

components/index/CardsFeatured/Stage/Table.vue
=> 旧指標(ステージ分類)を残す理由を注釈として追記

pages/cards/_card.vue
- close #2581 
- _cards に site-top-upper を組み込む
- rspec は pass 済み
=> _card にも site-top-upper を表示する

plugins/vue-chart.ts
- #2615 
- setTimeoutを$nextTickに置き換え
=> setTimeoutを$nextTickに置き換え

components/index/CardsFeatured/HealthBurden/Table.vue
- #2619 
- HealthBurden で確保数を超えたら赤くする
=> HealthBurden で確保数を超えたら赤くする

components/index/CardsFeatured/HealthBurden/Table.vue
=> HealthBurden 文言変更

components/index/CardsFeatured/HospitalCapacity/Beds.vue, spec/lib/HospitalCapacityCard.rb
- close #2638 
- HospicalCapacityCard の 残り床の計算式を変更
- rspec
=> HospicalCapacityCard の 残り床の計算式を変更

components/index/CardsReference/SelfDisclosures/Card.vue, components/index/CardsReference/WhatsNew/Card.vue, plugins/vue-chart.ts
- close #2678 
- sort() の中身をちゃんと書く
- fix lint
=> Firefoxでのsortの並び順を意図した順番にする

components/index/CardsFeatured/HomeCapacity/Beds.vue, components/index/CardsFeatured/HospitalCapacity/Beds.vue, components/index/CardsFeatured/HotelCapacity/Beds.vue
- #2677
- Windows + Chrome で、OSの言語を日本語に設定している場合に発生するようだ
- Windows + Chrome で、OSの言語をEnglishに設定している場合は枠に収まる
- 枠に収まるように微調整
=> セルに重なるカウント数のcssを調整

components/index/CardsFeatured/WeeklyMap/Iwate.vue
- #1559
- 200以上の場合は rgbAt(1) にする
=> 色分けのアルゴリズムを変更

components/index/CardsFeatured/HospitalCapacity/Beds.vue, spec/lib/HospitalCapacityCard.rb
- close #2694 
- 調整中の最後のコマにも数字を表示する
- rspec
=> 調整中の最後のコマにも数字を表示する

components/index/CardsFeatured/MonitoringConfirmedCasesNumberPer100k/Chart.vue, components/index/CardsMonitoring/AgeGroup/Chart.vue, components/index/CardsMonitoring/EffectiveReproductionNumber/Chart.vue, components/index/CardsMonitoring/HospitalizedNumber/Chart.vue, components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue, components/index/CardsMonitoring/PositiveRate/Chart.vue, components/index/CardsMonitoring/UntrackedRate/Chart.vue, components/index/CardsReference/SelfDisclosures/Card.vue, components/index/CardsReference/WhatsNew/Card.vue, components/index/_shared/TimeBarChart.vue, components/index/_shared/TimeStackedBarChart.vue, spec/lib/HospitalizedNumberCard.rb
- close #2678 
- fix sort bug
- sort improvement
=> Fix sort bug

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- #2710 
- `confirmed_case_area.json` を取得
=> add confirmed_case_area.json

components/index/CardsFeatured/MonitoringConfirmedCasesNumberPer100k/Chart.vue, components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue, components/index/CardsMonitoring/UntrackedRate/Chart.vue
=> 利用していないmethodsの削除

yarn.lock
=> chore: regenerate yarn.lock

components/index/CardsFeatured.vue
=> update first view card order

components/index/CardsFeatured/ConfirmedCasesArea/Chart.vue, components/index/CardsFeatured/MonitoringConfirmedCasesNumberPer100k/Chart.vue, components/index/CardsMonitoring/AgeGroup/Chart.vue, components/index/CardsMonitoring/EffectiveReproductionNumber/Chart.vue, components/index/CardsMonitoring/HealthBurdenHospital/Chart.vue, components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue, components/index/CardsMonitoring/PositiveRate/Chart.vue, components/index/CardsMonitoring/UntrackedRate/Chart.vue, components/index/_shared/TimeBarChart.vue, components/index/_shared/TimeStackedBarChart.vue
=> [bugfix] isBetweenの第３引数を'day'にする

components/index/CardsReference/SelfDisclosures/Table.vue, types/nuxtjs-gtm.d.ts
=> SelfDisclosuresにfilterを導入する

components/index/CardsReference/SelfDisclosures/Table.vue
=> update gtm event

components/index/CardsReference/SelfDisclosures/Table.vue
=> change event name

components/index/CardsFeatured/WeeklyMap/Iwate.vue
=> update map color

components/index/CardsFeatured/ConfirmedCasesArea/Chart.vue
=> update area chart yaxis

components/index/CardsReference/SelfDisclosures/Table.vue
=> change ga4 evnet name

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- #2222 
- ageについて生成済みのjsonを追加
=> confirmed_case_age.json を追加

components/index/CardsFeatured/ConfirmedCasesArea/Card.vue, components/index/CardsMonitoring/AgeGroup/Card.vue
- #2219 
- ブラウザのjsで計算するのではなく、計算済みの confirmed_case_age.json を使ってグラフを描く
=> ブラウザのjsで計算するのではなく、計算済みの confirmed_case_age.json を使ってグラフを描く

.eslintrc.js, package.json, yarn.lock
=> ビルド時のアクセシビリティlint導入の検討 の実装

components/index/CardsMonitoring/AgeGroup/Chart.vue
=> add age-chart pointRadius

Gemfile.lock
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> chore : bundle update

package.json
=> disable ie support

spec/feature/check_broken_links_spec.rb
=> microsoft の url は 200 じゃなくて 400 になってるので対応

components/index/CardsReference/SelfDisclosures/Table.vue, spec/feature/cards/cards_SelfDisclosuresCard_spec.rb, spec/lib/SelfDisclosuresCard.rb, spec/lib/TestedNumberCard.rb, utils/urls.ts
- close #2978 
- isSingleCard の時は items-per-page-options を 20 始まりにする
- isSingleCard の bugfix
- rspec の修正
=> SelfDisclosures で isSingleCard の時は items-per-page-options を 20 始まりにする 実装

pages/flow.vue
- #3036 
- fix styleling
- `Expected complex :not() pseudo-class notation  selector-not-notation`
=> fix styleling : selector-not-notation

.github/workflows/on_dispatch_from_googleSheetsMenu_development.yml, .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- #3121 
- confirmed_case_city.json をリポジトリに追加する
=> confirmed_case_city.json の追加

components/index/CardsFeatured/ConfirmedCasesArea/Card.vue
- #3106 
- データ構造(ラベル)の変更に対応
- confirmed_case_area.data.data => confirmed_case_area.data.last7ma
=> データ構造の変更に合わせる

nuxt.config.dev.ts, nuxt.config.ts
=> add clinic-map to nuxt.config

pages/flow.vue
- #3138 
- flow に clinic-map へのリンクを追加
=> clinic-map を flow に追加

components/index/CardsFeatured/AgeGroup/Chart.vue, components/index/CardsFeatured/ConfirmedCasesArea/Chart.vue, components/index/CardsFeatured/ConfirmedCasesAreaPer100k/Chart.vue, components/index/CardsMonitoring/HealthBurdenHospital/Chart.vue, components/index/CardsMonitoring/HospitalizedNumber/Chart.vue, components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue, components/index/CardsMonitoring/PositiveRate/Chart.vue, components/index/CardsMonitoring/UntrackedRate/Chart.vue, components/index/_shared/TimeBarChart.vue, components/index/_shared/TimeStackedBarChart.vue
- close #3155 
- 東京版 https://github.com/tokyo-metropolitan-gov/covid19/pull/7412
- `const chartData = this.chartData`
- アニメーションを切る
- rspec 通過の確認済
=> チャート描画の高速化

assets/locales/en.json, assets/locales/ja.json, components/index/CardsMonitoring/HospitalizedNumber/Card.vue, spec/lib/HospitalizedNumberCard.rb
- close #3202 
- #2561 
- notesに追記
=> 療養期間の短縮による自宅療養の減少をnotesに追記
