MeditationDuck/covid19

- pages/about.vue
MeditationDuck/covid19 が issue 開放されていないので issue 無し
- /about のページのgithubリポジトリのURLが東京版のまま
- 岩手版のリポジトリURLに変更
> github のリポジトリへのリンクを岩手版に変更

- utils/formatTestedCases.ts
MeditationDuck/covid19 が issue 開放されていないので issue 無し
- TestedCasesTable で 県内発生件数 が表示されない
- TestedCasesDetailsCard で 県内発生件数 が表示されない
- Data.inspection_status_summaryのラベル変更もれ
- data/data.json の inspection_status_summary の attr: "県内発生件数" に合うように utils/formatTestedCases の attr を修正
Before  
After
> 県内発生件数が表示されない

- components/DevelopmentModeMark.vue
- 下部に表示されているの「公開サイトへ」のリンク先が東京都のサイトになっていた
- DevelopmentModeMark.vueで該当部分のリンク先を岩手県版のサイトに修正
> development modeの公開サイトURLを岩手版に修正

- components/cards/ConsultationDeskReportsNumberCard.vue
- components/cards/TelephoneAdvisoryReportsNumberCard.vue
- close #9
- 「【帰国者・接触者相談センター】受付 相談件数」「（一般相談）受付への相談件数」に東京都のオープンデータサイトへのリンクが表示されていたため，削除した
> 東京都のオープンデータサイトへのリンクを削除する

- nuxt.config.ts
- close #11
- nuxt.config.ts に twitter:card の設定を追加
Before
After
> twitter card summary_large_image の meta タグを生成する設定

- auto-i18n/i18n_generator.py
https://github.com/MeditationDuck/covid19/issues/217
をとりあえず解消する
- close #217
> i18n_generator.py の None is not in list エラーへの対応

- components/ConfirmedCasesDetailsTable.vue
英語が単語の途中で改行されるようになるが、仕方ない。
- close #412 
- #0
- #0
- 英単語の途中でも改行が入るように css を調整
> ConfirmedCasesDetailsTable で英語の場合 文字が溢れる

- components/cards/PositiveRateCard.vue
weekly_average_diagnosed_count は PCR検査の7日間移動平均の数を表示する
- close #454
> fix: PositiveRateCardの項目名を変更

- components/cards/MonitoringConfirmedCasesNumberCard.vue
新規陽性者数
から
新規陽性者数の7日間平均
に変更
- close #461
> fix: MonitoringConfirmedCasesNumberCard の title を変更

- components/cards/ConfirmedCasesByMunicipalitiesCard.vue
- 東京のように地域区分を作っていないので「地域(area)」は「岩手県」固定となるので、非表示にする
- 市町村は ruby じゃなくて code でソートする
- close #492
> 陽性患者数（市町村別）で地域（岩手県）を非表示、codeでソート

- components/DataTable.vue
- components/cards/ConfirmedCasesAttributesCard.vue
- data_tools/google_sheets_to_data_json/generate_data_json.rb
- utils/formatTable.ts
- #485 
- 「陽性者の属性」で個別事例の退院○印を非表示にする
- 岩手県が個別の症状（軽症・中症・重症）を発表していないのでカウントできない
- 岩手県が個別の退院日を公表していないので Google Sheets の output_patients からカウントできないので、 Google Sheets の output_hospitalized_numbers で手動管理する値を採用する
> 個別の退院フラグを管理できないので、入院数・退院数を Google Sheets の output_hospitalized_numbers から計算する

- components/CardsReference.vue
- close #530 
- PositiveNumberByDiagnosedDateCardを非表示にする
- UntrackedRateCardを非表示にする
1日あたりの陽性者数が少ない現状では、あまり意味のない値を表示するカードを非表示にしておく。
1日あたりの陽性者数が増えてきたら、表示するようにする。
> Hide untracked rate card positive number by diagnosed date card

- components/cards/HospitalizedNumberCard.vue
現在の入院者数の数字を読み解く補助として、計画している病床数を掲載する
- close #576
> 入院患者数カードに、岩手県の病床確保計画の表を追加する

- components/cards/MonitoringConfirmedCasesNumberCard.vue
新規陽性者数の7日間平均の数字を読み解く補助として、岩手県のシナリオを掲載する。
- close #577
> 新規陽性者数の7日間平均に追加の説明文を掲載する

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/ogp_builder.yml
- .github/workflows/screenshot.yml
- .github/workflows/staging.yml
utils/formatDate.ts の .format(YYYY-MM-DD) などでJSTを前提にデータが用意されているのに、UTCで日付が計算されて、日付またぎが発生する
- close #625 
timezoneの問題で？
> 2020年9月4日の岩手県新型コロナウィルス最新状況は、陽性件数が1件・PCR検査が58件・抗原検査が15件・現在の入院患者は5人です。
になって欲しい部分が
> 2020年9月3日の岩手県新型コロナウィルス最新状況は、陽性件数が1件・PCR検査が58件・抗原検査が15件・現在の入院患者は5人です。
と、日付が1日遅れて計算されている。
> github action で yarn run generate するときのタイムゾーンをTokyoに設定

- .github/workflows/check_broken_links.yml
- .gitignore
- Gemfile
- Gemfile.lock
- spec/feature/check_broken_links_spec.rb
- spec/spec_helper.rb
- close #692 
- 盛岡市が公表している個別事例のURLが頻繁に変更される（どうかしてる）
- 旧URLから新URLにリダイレクトされないので、リンク先が404になる
- リンク切れをチェックしたい
- capybara + chrome + rspec で Vue.js を解釈した後のDOMで、a href のリンク切れをチェックする
- development に push されたら、github workflow で rspec を回す
- リンク切れが発生したら、check broken links の github action が fail するので、 Run failed: check broken links のメールが届く
- github action の ログを見ると、どのリンクが404なのか分かる
> 画面上のaタグのリンク切れをチェックする

- .github/workflows/check_broken_links.yml
- #692 
- github action の setup-ruby の仕様が変わったので ruby 2.7 と指定する
> fix: github action setup-ruby '2.7'

- components/WhatsNew.vue
- close #754 
- レイアウトCSS調整
- SPの場合はtimeをboldで表示
> Newsの本文が複数行になると、日付部分に回り込んで表示されている

- components/WhatsNew.vue
- close #764 
- #755 
- 同じ日のnewsがある場合は、Google Sheets の date を空にできるように対応。同日の先頭の項目だけ date を入力する
- text は「📞 」のように、絵文字 + 半角スペース でアイコンを入力するようにする
- PCとSPの見た目を調整
> WhatsNewのレイアウトを変更

- .github/workflows/i18n_generator.yml
- close #808 
- peter-evans/create-pull-request@v2 は
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
の deprecated の機能を使っているので actions がエラーになる。
- v3 にアップデートする。
> peter-evans/create-pull-request を v2 から v3 にアップデート

- .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
When using download-artifact@v1, a directory denoted by the name of the artifact would be created if the path input was not provided. All of the contents would be downloaded to this directory.
With v2, there is no longer an extra directory that is created if the path input is not provided. All the contents are downloaded to the current working directory.
- close #768
> download-artifact Compatibility between v1 and v2

- .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
- close #768 
- master の deploy における余計な build の削除
```
generate_ogp_master:
runs-on: macos-latest
```
の中で
- production のビルド
- OGPの生成
- 生成したOGPのコミット
- 生成された ./dist の production への action-gh-pages@v2
をやれば、もっと短縮できるけど、ubuntu-18.04 じゃなくて macos-latest 環境で生成されたものを production にしてもいいか？
> 余計な build の削除

- plugins/axe.ts
https://github.com/tokyo-metropolitan-gov/covid19/pull/5718/files
- close #896 
- https://github.com/tokyo-metropolitan-gov/covid19/issues/5717
- https://github.com/tokyo-metropolitan-gov/covid19/pull/5718
> perf: 本番環境で読み込むファイルから `axe-core` を分離する

- .github/workflows/on_pr_to_any_prlabeler.yml
- .github/workflows/on_pr_to_dev_reviewdog.yml
- .github/workflows/on_pr_to_stage_audit-staging.yml
- .github/workflows/on_push_to_dev_i18n_generator.yml
- close #911 
- ubuntu-latest を ubuntu-18.04 に変更
> workflow の ubuntu-latest が 18.04 から 20.04 に変更になるので 18.04 に固定

- nuxt.config.ts
// Since nuxt@2.14.5, there have been significant changes.
// We dealt with typical two (2) out of them:
// 1) The "mode:" directive got deprecated (seen right below);
// 2) Autoprefixer has been included so that we can lessen upgrade burden.
// mode: 'universal',
- close #937
> nuxt.config.ts から mode を削除

- nuxt.config.ts
- close #957
- #950
- #953 
- https://github.com/tokyo-metropolitan-gov/covid19/issues/5685
- https://github.com/tokyo-metropolitan-gov/covid19/pull/5701
- nuxt-purgecss の デフォルトの extractors を override して解決したはず
purgecssなし
purgecssあり
再び purgecss を効かせても、<style module> が消されずに残るようになった
> nuxt-purgecss導入で<style module>がpurgeされるのを修正

- components/cards/UntrackedRateCard.vue
- close #865 
- https://github.com/tokyo-metropolitan-gov/covid19/issues/5595
- 「増加比」ではなく「前週比」という言葉を使う
- サンプル数が少なく機能しないので、引き続き目立たない表示
> 接触歴不明者数で「増加比」ではなく「前週比」という言葉を使う

- .github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml
- .github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
- .github/workflows/on_pr_to_any_prlabeler.yml
- .github/workflows/on_pr_to_dev_reviewdog.yml
- .github/workflows/on_pr_to_stage_audit-staging.yml
- .github/workflows/on_push_to_dev_i18n_generator.yml
- .github/workflows/on_push_to_stage_staging.yml
- #768 
- github actions の環境を ubuntu-20.04 に変更
- ```https://www.mext.go.jp/content/20201203-mxt_kouhou01-000004520_01.pdf```のURLを```check_broken_links```する時に、www.mext.go.jp が 自ドメインのcertは送ってくるが、中間証明書のCybertrust Japan Public CA G3をbundleして送ってこないので、net/http とか wget でcertのverifyで失敗する。
- ubuntu-20.04ならCybertrust Japan Public CA G3が入っているのではないか期待。
- これで治らなかったら github actions 環境に Cybertrust Japan Public CA G3 の中間証明書をインストールする必要がある。
> github actions を ubuntu-18.04 から ubuntu-20.04 に変更

- components/ConfirmedCasesDetailsTable.vue
- close #856 
- 12月10日から死亡を退院等に含めずに発表するようになったため、レイアウト変更
> 死亡を退院等の子要素としない

- layouts/default.vue
- pages/cards/_card.vue
- close #1056 
- /pages/cards/_card.vue の description に updatedAt を入れない
- descriptionの文言を短く
> Update description text

- auto-i18n/i18n_generator.py
> quickfix: tagの中に小数点の . があると split されてしまう

- assets/variables.scss
- nuxt.config.dev.ts
- nuxt.config.ts
- close #1090 
- defaultAssetsをfalseにしないと、自動的にgoogle fontsを読み込むlink relが出力されて読み込みにいってしまう
- ベースの文字サイズはfont-size-rootで指定する
> defaultAssetsをfalseにして自動的にrobotoのlink relが生成されるのを防ぐ

- components/cards/TestedNumberCard.vue
- layouts/default.vue
- pages/cards/_card.vue
- close #1100 
- 各検査件数は positive_rate.json の個別値から計算する
- data.json の inspections_summary は削除する
> PCR検査件数と抗原検査件数はpositive_rate.jsonの個別値から計算する

- pages/index.vue
- #1143 
- 東京版と違いWhatsNewがCardsとしてtabの中にあるので、スクロールしてからlazyで読み込む方法は取らずに、最初からlazyで読み込む。mobileの場合のFirstContentfulPaintで不利になるが、現状ではこの実装。
> CardsTabの方でclient-onlyをする

- spec/feature/index_MonitoringConfirmedCasesNumberCard_spec.rb
- close #1105 
- close #1183 
- 直近1週間の新規患者数（対人口10万人） を計算してspec
> 直近1週間の新規患者数（対人口10万人）をspec

- spec/feature/index_PositiveRateCard_spec.rb
- spec/feature/index_UntrackedRateCard_spec.rb
- close #1196 
- 丸誤差の違いを吸収するためrspecの中でjsを実行した値を使う
> 3.05.toFixed(1)と3.05.round(1)の丸誤差の違い

- spec/lib/SiteTopUpper.rb
- #1105 
- .UpdatedAt の時刻の出力がjaとenでフォーマットが違う
> 日本語の時は %-H で英語の時は %H で出力される

- components/ScrollableChart.vue
- tsconfig.json
- close #1305 
- グラフの横幅をスマホは4、タブレットとPCは6に固定
- 利用していない is-weekly を削除
> グラフの横幅をスマホは4、タブレットとPCは6に固定

- components/cards/ConfirmedCasesByMunicipalitiesCard.vue
- #1327 
- Number()すると0.0が0になるのでrspecに引っかかる
> fix: getLast7DaysPer100k

- .eslintrc.js
```
Error: "prettier/vue" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
```
- #1340
> remove prettier/vue setting

- components/AppLink.vue
- components/CardsTab.vue
- components/ScrollableChart.vue
- nuxt-i18n.config.ts
- #1345 
- typescript 4.2.3 でのビルドエラーへの対応を追加
- import の .ts 拡張子を削除
- dateTimeFormatsCommon に 型を追加
> Typescript 4.2.3 でのビルドエラーへの対応(importで.ts拡張子を削除 / dateTimeFormatsCommonに型を追加)

- package.json
- yarn.lock
- #905 
- yarn.lock を削除して再生成しておく
- 現在のnuxtとbabel-preset-envの組み合わせでエラーが発生するため `yarn add -D @babel/preset-env@7.12.17` で babel/preset-env のバージョンを固定する
> yarn.lock の再生成

- layouts/default.vue
- close #1401 
- #1112 
- Service Workerが登録済の環境の人のブラウザから、Service Workerを登録解除する
このコードによって、sw.js が Service Worker から登録解除される
> Service Workerを登録解除するスクリプトを追加

- .eslintrc.js
- nuxt.config.dev.ts
- nuxt.config.ts
- plugins/vue-chart.ts
> 相対パスによる import を禁止するため .eslintrc.js の設定を追加／相対パスによる import をしている箇所を修正

- layouts/default.vue
- nuxt.config.dev.ts
- nuxt.config.ts
- spec/feature/check_unregister_serviceworker_spec.rb
- #1401 
- https://github.com/tokyo-metropolitan-gov/covid19/pull/6155
- 独自実装から nuxt-pwa を使った実装に変更する
> ServiceWorkerの登録解除する方法を東京版に合わせる

- spec/feature/check_broken_links_spec.rb
- spec/lib/SiteTopUpper.rb
- #1105 
- check_broken_linkで拒否られる場合があるっぽいのでUserAgentを追加
> check_broken_linkで拒否られる場合があるっぽいのでUserAgentを追加

- components/ConfirmedCasesDetailsTable.vue
- #1479 
- iPhone で [ +10 ] が改行していたので no-wrap
> fix: layout no-wrap

- components/WeeklyMap.vue
- #1569 
- 色の生成を`d3.scaleSequential(d3.interpolateReds)`にすると、陽性数が`0`の場合でも淡い色が着く
- 陽性数が`0`の市町村は #fff で描画して0であることを、より分かりやすくなるように、色生成の方法を調整
Before
After
> weekly_mapで陽性数が0の場合は fff にする

- components/WeeklyMap.vue
ちょっとデザインの変更をしてみました。
- #1569 
- #1559 
- 666の3pxだと目立ちすぎる感じがするので、少し控えめに調整
> #1569 マウスオーバーで市町村のボーダーの色を999・太さ2pxに調整

- components/WeeklyMap.vue
- #1559
- #1560, #1563, #1566
- 地図上でマウスオーバーした際に，市町村の色が変わるのではなく，ボーダーの色と太さが変わるように変更
- 修正前は，盛岡市にマウスオーバーすると宮古市と同じような色になったり，岩泉町にマウスオーバーすると久慈市と同じような色になったりして違和感があったため
> 市町村ごとの感染状況を地図の塗り分けで表現: マウスオーバー時のスタイルを変更

- spec/spec_helper.rb
- #1105 
- rspecのcapybaraのchromeでGoogleAnalyticsを回避する
> CapybaraのChrome起動オプションでGoogle Analyticsを明示的に迂回する

- Gemfile
- Gemfile.lock
- layouts/default.vue
- pages/cards/_card.vue
- spec/feature/cards/cards_ConfirmedCasesAttributesCard_spec.rb
- spec/feature/cards/cards_ConfirmedCasesByMunicipalitiesCard_spec.rb
- spec/feature/cards/cards_ConfirmedCasesDetailsCard_spec.rb
- spec/feature/cards/cards_ConfirmedCasesNumberCard_spec.rb
- spec/feature/cards/cards_HospitalizedNumberCard_spec.rb
- spec/feature/cards/cards_MonitoringConfirmedCasesNumberCard_spec.rb
- spec/feature/cards/cards_MonitoringConsultationDeskReportsNumberCard_spec.rb
- spec/feature/cards/cards_PositiveRateCard_spec.rb
- spec/feature/cards/cards_SelfDisclosuresCard_spec.rb
- spec/feature/cards/cards_TelephoneAdvisoryReportsNumberCard_spec.rb
- spec/feature/cards/cards_TestedNumberCard_spec.rb
- spec/feature/cards/cards_UntrackedRateCard_spec.rb
- spec/feature/cards/cards_WhatsNewCard_spec.rb
- spec/feature/index/index_h1h2_spec.rb
- spec/spec_helper.rb
- close #1621 
- ` | ` をやめる方向で解決
> og:title をサイト全体で同じ文言に設定する

- assets/locales/en.json
- assets/locales/ja.json
- components/DataTable.vue
- components/DataViewDataSetPanel.vue
- components/SelfDisclosures.vue
- components/WhatsNew.vue
- components/cards/SelfDisclosuresCard.vue
- spec/lib/ConfirmedCasesAttributesCard.rb
- spec/lib/SelfDisclosuresCard.rb
- spec/lib/WhatsNewCard.rb
- close #1523 
- SelfDisclosuresCard.vue 用に Whatsnew.vue から SelfDisclosures.vue に分離
- 情報提供フォームはDataSetPanelの部分に表示する
- Whatsnew と SelfDisclosures に ページネーションを追加
- 関連する spec
> Whatsnew と SelfDisclosures に ページネーションを追加

- spec/lib/PositiveRateCard.rb
- close #1637 
- PositiveRate_spec の 20210214 と 20210505 を特別対応
> 陽性者数 > 検査件数 になった場合の 20210214 と 20210505 を特別対応

- components/CardsReference.vue
- components/SiteTopUpper.vue
- spec/lib/SiteTopUpper.rb
- spec/spec_helper.rb
- close #1657 
- alertItems を日付でソートせずに、GoogleSheetの順序のまま扱う
> Feature/#1657 画面遷移して戻るとalert itemsの順序が逆に表示されている

- spec/lib/PositiveRateCard.rb
- #1637
- #1640 
- specの検査の陽性率の計算を微調整
> spec: 検査の陽性率の計算式で個別に / 7.0 をせずに最後に a / b する

- components/SideNavigation.vue
- pages/vaccine.vue
- close #1660
- (なし)
- ワクチン接種情報を別ページに分離し、サイドバーの「ワクチン接種」のリンクから飛べるようにしました。
> サイドナビゲーションのワクチン接種情報を別ページに分離しました

- ui-test/ogp_composite_weekly_map.js
- close #1681 
- retina環境で開発してたら画像がx2で計算してた。github actions は x1環境だった
> fix: github actions 環境は retina じゃなかった

- layouts/print.vue
- spec/feature/page/page_print_flow_spec.rb
- close #1716 
- printのh1の翻訳キーがtypo を修正
- printのh1の翻訳キーがtypo に対する spec
> printのh1の翻訳キーがtypo を修正

- components/DataTable.vue
- pages/cards/_card.vue
- close #1731 
- data-table の pagination を右づめにする
- /cards/ の時に DataCard の余白が小さくなっていたのを（とりあえず無理矢理）修正
> Update table paginations css

- components/DataTable.vue
- components/DataView.vue
- utils/formatTable.ts
- close #1738 
- #1731 
- 接触歴とYouTubeリンクは align center にする
- スマホの .DataView-Inner の左右のpaddingをちょっと狭く
- スマホでのDataTableの余白を調整
- DataTableのfooterをできるだけ1行に収まるように調整
> DataTableのレイアウト調整

- pages/worker.vue
- close #1736 
- https://iwate.stopcovid19.jp/worker/ から[岩手県新型コロナウイルス感染症対応従事者慰労金交付事業のお知らせ](https://www.pref.iwate.jp/kurashikankyou/iryou/seido/1031487.html) へのリンクを削除する
cf. https://iwate.stopcovid19.jp/worker/
> 「岩手県新型コロナウイルス感染症対応従事者慰労金交付事業のお知らせ」へのリンクを削除

- nuxt-i18n.config.ts
- close #1751 
- `hour12: false` から `hourCycle: 'h23'` に変更
> nuxt-i18nにhour12じゃなくてhourCycle: 'h23' を指定する

- pages/cards/_card.vue
- spec/feature/cards/cards_ConfirmedCasesAttributesCard_spec.rb
- spec/feature/cards/cards_ConfirmedCasesByMunicipalitiesCard_spec.rb
- spec/feature/cards/cards_ConfirmedCasesDetailsCard_spec.rb
- spec/feature/cards/cards_ConfirmedCasesNumberCard_spec.rb
- spec/feature/cards/cards_HospitalizedNumberCard_spec.rb
- spec/feature/cards/cards_MonitoringConfirmedCasesNumberCard_spec.rb
- spec/feature/cards/cards_PositiveRateCard_spec.rb
- spec/feature/cards/cards_SelfDisclosuresCard_spec.rb
- spec/feature/cards/cards_TestedNumberCard_spec.rb
- spec/feature/cards/cards_UntrackedRateCard_spec.rb
- spec/feature/cards/cards_WeeklyMapCard_spec.rb
- spec/feature/cards/cards_WhatsNewCard_spec.rb
- spec/feature/index/index_h1h2_spec.rb
- utils/i18nUtils.ts
- close #1763 
- og:url の末尾を `//` から `/` に修正
- og:url の末尾を `//` から `/` に修正 に対する spec
- ついでに alternate-hreflang- の末尾に `/` を追加
> og:url の末尾が `//` になってるのを `/` に修正

- components/DataViewShare.vue
- close #1726 
- シェアシートのpermalinkの末尾に`/`をつける
> シェアシートのpermalinkの末尾に`/`をつける

- spec/feature/cards/cards_MonitoringConfirmedCasesNumberPer100kCard_spec.rb
- spec/feature/index/index_MonitoringConfirmedCasesNumberPer100kCard_spec.rb
- spec/lib/MonitoringConfirmedCasesNumberPer100kCard.rb
- #1823 
- #1105 
- MonitoringConfirmedCasesNumberPer100kCard に対する rspec を追加
> MonitoringConfirmedCasesNumberPer100kCard に対する rspec を追加

- spec/lib/MonitoringConfirmedCasesNumberCard.rb
- #1105 
- js側の実装が四捨五入じゃなくて .toFixed(1) なので、specの中で使う値もjsで .toFixed(1) しないと異なる場合がある
- 直近1週間の新規患者数（対人口10万人）の数をrubyで計算した結果をjsで .toFixed(1)する
> 直近1週間の新規患者数（対人口10万人）の数をrubyで計算した結果をjsで .toFixed(1)する

- assets/locales/en.json
- #1681 
- enのOGP画像のURLが404だったので、日本語版のURLをとりあえず指定
> en の OGP画像のurlを修正

- components/index/CardsMonitoring/AgeGroup/Chart.vue
- components/index/CardsMonitoring/EffectiveReproductionNumber/Chart.vue
- components/index/CardsMonitoring/HospitalizedNumber/Chart.vue
- components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue
- components/index/CardsMonitoring/MonitoringConfirmedCasesNumberPer100k/Chart.vue
- components/index/CardsMonitoring/PositiveRate/Chart.vue
- components/index/CardsMonitoring/UntrackedRate/Chart.vue
- components/index/_shared/TimeBarChart.vue
- components/index/_shared/TimeStackedBarChart.vue
- close #2265 
- https://github.com/tokyo-metropolitan-gov/covid19/issues/2384
- day軸は生成はするが非表示にする。
- 削除すると https://github.com/tokyo-metropolitan-gov/covid19/issues/2384 のように見切れる問題が発生する
> chartから id:'day' を非表示にする

- components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue
- components/index/CardsMonitoring/MonitoringConfirmedCasesNumberPer100k/Chart.vue
- #2188 
- 対人口10万人グラフに県独自の緊急事態宣言の解除annotationを追加
> 対人口10万人グラフに県独自の緊急事態宣言の解除annotationを追加

- stylelint.config.js
- #2431 
- https://github.com/prettier/stylelint-config-prettier/pull/129/commits/d852c75910c0fe7c6ca97672a6d6639df1289861
- stylelintのデフォルト設定に入ったので、独自の設定からは削除
> stylelint 9.0.3 で at-rule-empty-line-before がデフォルト設定に戻った

- pages/cards/_card.vue
- close #2581 
- _card に site-top-upper を表示しつつOGPとembedの時は表示しない
> _card に site-top-upper を表示しつつOGPの時は表示しない

- components/index/CardsFeatured/MonitoringConfirmedCasesNumberPer100k/Chart.vue
- #2538 
- per100k の max を 50 に設定
> per100kチャートのyaxisのmaxを50に設定

- components/index/_shared/DateRangeSlider.vue
- #2615 
- 東京版はbaseが10で、岩手版は16なので、0.75remに設定して、東京版と同じ大きさにする
> fix range slider css

- components/index/CardsFeatured/ConfirmedCasesArea/Card.vue
- components/index/CardsFeatured/ConfirmedCasesDetails/Card.vue
- components/index/CardsFeatured/HealthBurden/Card.vue
- components/index/CardsFeatured/HomeCapacity/Card.vue
- components/index/CardsFeatured/HospitalCapacity/Card.vue
- components/index/CardsFeatured/HotelCapacity/Card.vue
- components/index/CardsFeatured/MonitoringConfirmedCasesNumberPer100k/Card.vue
- components/index/CardsFeatured/Stage/Card.vue
- components/index/CardsMonitoring/AgeGroup/Card.vue
- components/index/CardsMonitoring/ConfirmedCasesNumber/Card.vue
- components/index/CardsMonitoring/EffectiveReproductionNumber/Card.vue
- components/index/CardsMonitoring/HealthBurdenHospital/Card.vue
- components/index/CardsMonitoring/HospitalizedNumber/Card.vue
- components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Card.vue
- components/index/CardsMonitoring/PositiveRate/Card.vue
- components/index/CardsMonitoring/TestedNumber/Card.vue
- components/index/CardsMonitoring/UntrackedRate/Card.vue
- components/index/CardsReference/ConfirmedCasesAttributes/Card.vue
- components/index/CardsReference/ConfirmedCasesByMunicipalities/Card.vue
- components/index/CardsReference/IwateNinshou/Restaurant/Card.vue
- components/index/CardsReference/SelfDisclosures/Card.vue
- components/index/CardsReference/WhatsNew/Card.vue
- pages/cards/_card.vue
- utils/urls.ts
- close #2751 
- https://github.com/tokyo-metropolitan-gov/covid19/pull/6599
- カード単体表示 かつ breakpoint.mdAndUp (タブレット横以上)のときグラフの初期表示期間を２倍（120日分）にする
> カード単体表示 かつ breakpoint.mdAndUp (タブレット横以上)のときグラフの初期表示期間を２倍（120日分）にする

- components/index/CardsFeatured/MonitoringConfirmedCasesNumberPer100k/Chart.vue
- components/index/CardsMonitoring/AgeGroup/Chart.vue
- components/index/CardsMonitoring/EffectiveReproductionNumber/Chart.vue
- close #3099 
- グラフの縦軸の max の値を調整して見やすくする
> scaledTicksYAxisMax の値を調整

- assets/locales/ja.json
- pages/flow.vue
- close #3243 
- 相談窓口の電話番号を「いわて健康フォローアップセンター」の番号に変更
- 検査キット送付センターについて掲載
> 相談窓口の電話番号を「いわて健康フォローアップセンター」の番号に変更
